openapi: 3.1.0
info:
  title: Outcomeo - ACCA Exam Coach API
  description: |
    Backend API for Outcomeo ACCA exam preparation platform.
    Provides user management, study planning, content delivery, session tracking, analytics, and premium subscriptions.
    
    **Authentication:** All endpoints use Bearer token authentication with Supabase service role key.
  version: 1.0.0
  contact:
    name: Outcomeo Support
    email: support@outcomeo.com

servers:
  - url: https://irlxegoatcgskhdvbvuo.supabase.co/functions/v1
    description: Production Supabase Edge Functions

security:
  - bearerAuth: []

paths:
  /users-get-or-create:
    post:
      operationId: getUserOrCreate
      summary: Get or create an Outcomeo user
      description: |
        Retrieves an existing user by email, or creates a new user if one doesn't exist.
        Use this endpoint when a student first interacts with Outcomeo or updates their exam details.
      tags:
        - User Management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: Student's email address (primary identifier)
                  example: student@example.com
                exam_paper:
                  type: string
                  description: ACCA paper code (e.g., BT, MA, FA, LW, PM, TX, FR, FM, AA, AAA)
                  example: BT
                exam_date:
                  type: string
                  format: date
                  description: Planned exam date in YYYY-MM-DD format
                  example: "2025-06-15"
                weekly_study_hours:
                  type: integer
                  description: Hours per week the student plans to study
                  minimum: 1
                  maximum: 40
                  default: 5
                  example: 10
      responses:
        '200':
          description: User retrieved or created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique user identifier
                  email:
                    type: string
                    format: email
                  exam_paper:
                    type: string
                    nullable: true
                  exam_date:
                    type: string
                    format: date
                    nullable: true
                  weekly_study_hours:
                    type: integer
                  subscription_status:
                    type: string
                    enum: [free, premium]
                    description: Current subscription tier
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid request (missing email)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /plans-today-tasks:
    get:
      operationId: getTodayTasks
      summary: Generate today's study plan
      description: |
        Returns a personalized daily study plan based on the user's exam paper, 
        weekly study hours, and current progress. Uses a simple rotation algorithm
        through syllabus units.
      tags:
        - Study Planning
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: User's unique identifier from users-get-or-create
      responses:
        '200':
          description: Study plan generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  paper:
                    type: string
                    description: ACCA paper code
                    example: BT
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        unit_code:
                          type: string
                          description: Syllabus unit code
                          example: BT01
                        type:
                          type: string
                          enum: [mcq, flashcard]
                          description: Question type
                        difficulty:
                          type: string
                          enum: [easy, medium, hard]
                          description: Difficulty level
                        count:
                          type: integer
                          description: Number of questions to complete
                          example: 10
        '400':
          description: Missing or invalid userId
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /content-batch:
    post:
      operationId: getContentBatch
      summary: Fetch a batch of study questions
      description: |
        Retrieves a randomized set of questions from the question bank based on filters.
        Use this to get questions for practice sessions, quizzes, or mock exams.
      tags:
        - Content Delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - paper
                - size
              properties:
                paper:
                  type: string
                  description: ACCA paper code
                  example: BT
                unit_code:
                  type: string
                  description: Optional filter by syllabus unit
                  example: BT01
                type:
                  type: string
                  enum: [mcq, flashcard]
                  description: Optional filter by question type
                difficulty:
                  type: string
                  enum: [easy, medium, hard]
                  description: Optional filter by difficulty
                size:
                  type: integer
                  minimum: 1
                  maximum: 100
                  description: Number of questions to return
                  example: 10
      responses:
        '200':
          description: Questions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    paper:
                      type: string
                    unit_code:
                      type: string
                      nullable: true
                    type:
                      type: string
                    difficulty:
                      type: string
                      nullable: true
                    question:
                      type: string
                    options:
                      type: array
                      nullable: true
                      description: Answer options (for MCQs)
                      items:
                        type: string
                    answer:
                      type: string
                      nullable: true
                    correct_option_index:
                      type: integer
                      nullable: true
                    explanation:
                      type: string
                      description: Detailed explanation of the answer
                      nullable: true
        '400':
          description: Invalid request (missing required fields or size out of range)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /sessions-log:
    post:
      operationId: logStudySession
      summary: Log a completed study session
      description: |
        Records session details including questions attempted, accuracy, and raw performance data.
        Use this after every study session to track progress and calculate analytics.
      tags:
        - Session Tracking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - session_type
              properties:
                userId:
                  type: string
                  format: uuid
                  description: User's unique identifier
                session_type:
                  type: string
                  enum: [onboarding, daily, quick_drill, mini_test, mock_exam]
                  description: Type of study session
                  example: daily
                total_questions:
                  type: integer
                  description: Total number of questions attempted
                  default: 0
                  example: 10
                correct_answers:
                  type: integer
                  description: Number of correct answers
                  default: 0
                  example: 7
                raw_log:
                  type: array
                  description: Detailed per-question log for analytics
                  items:
                    type: object
                    properties:
                      question_id:
                        type: string
                        format: uuid
                      unit_code:
                        type: string
                      difficulty:
                        type: string
                      correct:
                        type: boolean
                      time_spent:
                        type: integer
                        description: Time in seconds
      responses:
        '200':
          description: Session logged successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  user_id:
                    type: string
                    format: uuid
                  session_type:
                    type: string
                  started_at:
                    type: string
                    format: date-time
                  ended_at:
                    type: string
                    format: date-time
                  total_questions:
                    type: integer
                  correct_answers:
                    type: integer
                  raw_log:
                    type: array
                    nullable: true
                    items:
                      type: object
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid request (missing required fields or invalid session_type)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /analytics-summary:
    get:
      operationId: getAnalyticsSummary
      summary: Get user analytics summary
      description: |
        Returns overall study performance metrics including accuracy by unit and difficulty.
        Use this to show progress charts and identify weak areas.
      tags:
        - Analytics
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: User's unique identifier
      responses:
        '200':
          description: Analytics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_questions:
                    type: integer
                    description: Total questions answered across all sessions
                    example: 250
                  overall_accuracy:
                    type: integer
                    description: Overall accuracy percentage
                    example: 72
                  by_unit:
                    type: object
                    description: Accuracy percentage by unit code
                    additionalProperties:
                      type: integer
                    example:
                      BT01: 85
                      BT02: 68
                      BT03: 75
                  by_difficulty:
                    type: object
                    description: Accuracy percentage by difficulty level
                    additionalProperties:
                      type: integer
                    example:
                      easy: 92
                      medium: 71
                      hard: 58
        '400':
          description: Missing or invalid userId
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /stripe-create-checkout-link:
    post:
      operationId: createCheckoutLink
      summary: Create Stripe checkout session
      description: |
        Creates a Stripe checkout session for premium subscription upgrade.
        Returns a URL to redirect the user to Stripe's hosted checkout page.
      tags:
        - Premium Subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                  format: uuid
                  description: User's unique identifier
      responses:
        '200':
          description: Checkout session created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
                    description: Stripe checkout URL to redirect user to
                    example: https://checkout.stripe.com/pay/cs_test_...
        '400':
          description: Invalid request (missing userId)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Use your Supabase service role key as the Bearer token

tags:
  - name: User Management
    description: User profile creation and retrieval
  - name: Study Planning
    description: Personalized daily study plan generation
  - name: Content Delivery
    description: Question bank and content retrieval
  - name: Session Tracking
    description: Study session logging and history
  - name: Analytics
    description: Performance analytics and insights
  - name: Premium Subscription
    description: Premium upgrade and billing management
